/* Auto-generated by genmsg_cpp for file /home/gaudi/ros_workspace/lynxmotion/msg/aceleracion.msg */
#ifndef LYNXMOTION_MESSAGE_ACELERACION_H
#define LYNXMOTION_MESSAGE_ACELERACION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace lynxmotion
{
template <class ContainerAllocator>
struct aceleracion_ {
  typedef aceleracion_<ContainerAllocator> Type;

  aceleracion_()
  : aX(0.0)
  , aY(0.0)
  , aZ(0.0)
  , aX0(0.0)
  , aY0(0.0)
  , aZ0(0.0)
  {
  }

  aceleracion_(const ContainerAllocator& _alloc)
  : aX(0.0)
  , aY(0.0)
  , aZ(0.0)
  , aX0(0.0)
  , aY0(0.0)
  , aZ0(0.0)
  {
  }

  typedef double _aX_type;
  double aX;

  typedef double _aY_type;
  double aY;

  typedef double _aZ_type;
  double aZ;

  typedef double _aX0_type;
  double aX0;

  typedef double _aY0_type;
  double aY0;

  typedef double _aZ0_type;
  double aZ0;


private:
  static const char* __s_getDataType_() { return "lynxmotion/aceleracion"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "50bfd313ab91fdbcdfc22f6f4506e689"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 aX\n\
float64 aY\n\
float64 aZ\n\
float64 aX0\n\
float64 aY0\n\
float64 aZ0\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, aX);
    ros::serialization::serialize(stream, aY);
    ros::serialization::serialize(stream, aZ);
    ros::serialization::serialize(stream, aX0);
    ros::serialization::serialize(stream, aY0);
    ros::serialization::serialize(stream, aZ0);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, aX);
    ros::serialization::deserialize(stream, aY);
    ros::serialization::deserialize(stream, aZ);
    ros::serialization::deserialize(stream, aX0);
    ros::serialization::deserialize(stream, aY0);
    ros::serialization::deserialize(stream, aZ0);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(aX);
    size += ros::serialization::serializationLength(aY);
    size += ros::serialization::serializationLength(aZ);
    size += ros::serialization::serializationLength(aX0);
    size += ros::serialization::serializationLength(aY0);
    size += ros::serialization::serializationLength(aZ0);
    return size;
  }

  typedef boost::shared_ptr< ::lynxmotion::aceleracion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lynxmotion::aceleracion_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct aceleracion
typedef  ::lynxmotion::aceleracion_<std::allocator<void> > aceleracion;

typedef boost::shared_ptr< ::lynxmotion::aceleracion> aceleracionPtr;
typedef boost::shared_ptr< ::lynxmotion::aceleracion const> aceleracionConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::lynxmotion::aceleracion_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::lynxmotion::aceleracion_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace lynxmotion

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::lynxmotion::aceleracion_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::lynxmotion::aceleracion_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::lynxmotion::aceleracion_<ContainerAllocator> > {
  static const char* value() 
  {
    return "50bfd313ab91fdbcdfc22f6f4506e689";
  }

  static const char* value(const  ::lynxmotion::aceleracion_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x50bfd313ab91fdbcULL;
  static const uint64_t static_value2 = 0xdfc22f6f4506e689ULL;
};

template<class ContainerAllocator>
struct DataType< ::lynxmotion::aceleracion_<ContainerAllocator> > {
  static const char* value() 
  {
    return "lynxmotion/aceleracion";
  }

  static const char* value(const  ::lynxmotion::aceleracion_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::lynxmotion::aceleracion_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 aX\n\
float64 aY\n\
float64 aZ\n\
float64 aX0\n\
float64 aY0\n\
float64 aZ0\n\
\n\
\n\
";
  }

  static const char* value(const  ::lynxmotion::aceleracion_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::lynxmotion::aceleracion_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::lynxmotion::aceleracion_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.aX);
    stream.next(m.aY);
    stream.next(m.aZ);
    stream.next(m.aX0);
    stream.next(m.aY0);
    stream.next(m.aZ0);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct aceleracion_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lynxmotion::aceleracion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::lynxmotion::aceleracion_<ContainerAllocator> & v) 
  {
    s << indent << "aX: ";
    Printer<double>::stream(s, indent + "  ", v.aX);
    s << indent << "aY: ";
    Printer<double>::stream(s, indent + "  ", v.aY);
    s << indent << "aZ: ";
    Printer<double>::stream(s, indent + "  ", v.aZ);
    s << indent << "aX0: ";
    Printer<double>::stream(s, indent + "  ", v.aX0);
    s << indent << "aY0: ";
    Printer<double>::stream(s, indent + "  ", v.aY0);
    s << indent << "aZ0: ";
    Printer<double>::stream(s, indent + "  ", v.aZ0);
  }
};


} // namespace message_operations
} // namespace ros

#endif // LYNXMOTION_MESSAGE_ACELERACION_H

