/* Auto-generated by genmsg_cpp for file /home/gaudi/ros_workspace/lynxmotion/msg/angulos.msg */
#ifndef LYNXMOTION_MESSAGE_ANGULOS_H
#define LYNXMOTION_MESSAGE_ANGULOS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace lynxmotion
{
template <class ContainerAllocator>
struct angulos_ {
  typedef angulos_<ContainerAllocator> Type;

  angulos_()
  : Roll(0.0)
  , Pitch(0.0)
  {
  }

  angulos_(const ContainerAllocator& _alloc)
  : Roll(0.0)
  , Pitch(0.0)
  {
  }

  typedef float _Roll_type;
  float Roll;

  typedef float _Pitch_type;
  float Pitch;


private:
  static const char* __s_getDataType_() { return "lynxmotion/angulos"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "4dc8074cd743b9ac988e29a3793a37de"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float32 Roll\n\
float32 Pitch\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, Roll);
    ros::serialization::serialize(stream, Pitch);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, Roll);
    ros::serialization::deserialize(stream, Pitch);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(Roll);
    size += ros::serialization::serializationLength(Pitch);
    return size;
  }

  typedef boost::shared_ptr< ::lynxmotion::angulos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lynxmotion::angulos_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct angulos
typedef  ::lynxmotion::angulos_<std::allocator<void> > angulos;

typedef boost::shared_ptr< ::lynxmotion::angulos> angulosPtr;
typedef boost::shared_ptr< ::lynxmotion::angulos const> angulosConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::lynxmotion::angulos_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::lynxmotion::angulos_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace lynxmotion

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::lynxmotion::angulos_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::lynxmotion::angulos_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::lynxmotion::angulos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4dc8074cd743b9ac988e29a3793a37de";
  }

  static const char* value(const  ::lynxmotion::angulos_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4dc8074cd743b9acULL;
  static const uint64_t static_value2 = 0x988e29a3793a37deULL;
};

template<class ContainerAllocator>
struct DataType< ::lynxmotion::angulos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "lynxmotion/angulos";
  }

  static const char* value(const  ::lynxmotion::angulos_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::lynxmotion::angulos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 Roll\n\
float32 Pitch\n\
\n\
\n\
";
  }

  static const char* value(const  ::lynxmotion::angulos_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::lynxmotion::angulos_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::lynxmotion::angulos_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.Roll);
    stream.next(m.Pitch);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct angulos_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lynxmotion::angulos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::lynxmotion::angulos_<ContainerAllocator> & v) 
  {
    s << indent << "Roll: ";
    Printer<float>::stream(s, indent + "  ", v.Roll);
    s << indent << "Pitch: ";
    Printer<float>::stream(s, indent + "  ", v.Pitch);
  }
};


} // namespace message_operations
} // namespace ros

#endif // LYNXMOTION_MESSAGE_ANGULOS_H

