/* Auto-generated by genmsg_cpp for file /home/gaudi/ros_workspace/lynxmotion/msg/commData.msg */
#ifndef LYNXMOTION_MESSAGE_COMMDATA_H
#define LYNXMOTION_MESSAGE_COMMDATA_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace lynxmotion
{
template <class ContainerAllocator>
struct commData_ {
  typedef commData_<ContainerAllocator> Type;

  commData_()
  : data(0)
  {
  }

  commData_(const ContainerAllocator& _alloc)
  : data(0)
  {
  }

  typedef uint8_t _data_type;
  uint8_t data;


private:
  static const char* __s_getDataType_() { return "lynxmotion/commData"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "1bf77f25acecdedba0e224b162199717"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "char data\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, data);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, data);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(data);
    return size;
  }

  typedef boost::shared_ptr< ::lynxmotion::commData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lynxmotion::commData_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct commData
typedef  ::lynxmotion::commData_<std::allocator<void> > commData;

typedef boost::shared_ptr< ::lynxmotion::commData> commDataPtr;
typedef boost::shared_ptr< ::lynxmotion::commData const> commDataConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::lynxmotion::commData_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::lynxmotion::commData_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace lynxmotion

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::lynxmotion::commData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::lynxmotion::commData_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::lynxmotion::commData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1bf77f25acecdedba0e224b162199717";
  }

  static const char* value(const  ::lynxmotion::commData_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1bf77f25acecdedbULL;
  static const uint64_t static_value2 = 0xa0e224b162199717ULL;
};

template<class ContainerAllocator>
struct DataType< ::lynxmotion::commData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "lynxmotion/commData";
  }

  static const char* value(const  ::lynxmotion::commData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::lynxmotion::commData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "char data\n\
\n\
";
  }

  static const char* value(const  ::lynxmotion::commData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::lynxmotion::commData_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::lynxmotion::commData_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.data);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct commData_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lynxmotion::commData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::lynxmotion::commData_<ContainerAllocator> & v) 
  {
    s << indent << "data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data);
  }
};


} // namespace message_operations
} // namespace ros

#endif // LYNXMOTION_MESSAGE_COMMDATA_H

