/* Auto-generated by genmsg_cpp for file /home/gaudi/ros_workspace/lynxmotion/msg/motores.msg */
#ifndef LYNXMOTION_MESSAGE_MOTORES_H
#define LYNXMOTION_MESSAGE_MOTORES_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace lynxmotion
{
template <class ContainerAllocator>
struct motores_ {
  typedef motores_<ContainerAllocator> Type;

  motores_()
  : q1(0.0)
  , q2(0.0)
  , q3(0.0)
  , q4(0.0)
  , q5(0.0)
  {
  }

  motores_(const ContainerAllocator& _alloc)
  : q1(0.0)
  , q2(0.0)
  , q3(0.0)
  , q4(0.0)
  , q5(0.0)
  {
  }

  typedef float _q1_type;
  float q1;

  typedef float _q2_type;
  float q2;

  typedef float _q3_type;
  float q3;

  typedef float _q4_type;
  float q4;

  typedef float _q5_type;
  float q5;


private:
  static const char* __s_getDataType_() { return "lynxmotion/motores"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "b62a1c74640995c39e75f3dbdb456df4"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float32 q1\n\
float32 q2\n\
float32 q3\n\
float32 q4\n\
float32 q5\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, q1);
    ros::serialization::serialize(stream, q2);
    ros::serialization::serialize(stream, q3);
    ros::serialization::serialize(stream, q4);
    ros::serialization::serialize(stream, q5);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, q1);
    ros::serialization::deserialize(stream, q2);
    ros::serialization::deserialize(stream, q3);
    ros::serialization::deserialize(stream, q4);
    ros::serialization::deserialize(stream, q5);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(q1);
    size += ros::serialization::serializationLength(q2);
    size += ros::serialization::serializationLength(q3);
    size += ros::serialization::serializationLength(q4);
    size += ros::serialization::serializationLength(q5);
    return size;
  }

  typedef boost::shared_ptr< ::lynxmotion::motores_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lynxmotion::motores_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct motores
typedef  ::lynxmotion::motores_<std::allocator<void> > motores;

typedef boost::shared_ptr< ::lynxmotion::motores> motoresPtr;
typedef boost::shared_ptr< ::lynxmotion::motores const> motoresConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::lynxmotion::motores_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::lynxmotion::motores_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace lynxmotion

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::lynxmotion::motores_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::lynxmotion::motores_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::lynxmotion::motores_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b62a1c74640995c39e75f3dbdb456df4";
  }

  static const char* value(const  ::lynxmotion::motores_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb62a1c74640995c3ULL;
  static const uint64_t static_value2 = 0x9e75f3dbdb456df4ULL;
};

template<class ContainerAllocator>
struct DataType< ::lynxmotion::motores_<ContainerAllocator> > {
  static const char* value() 
  {
    return "lynxmotion/motores";
  }

  static const char* value(const  ::lynxmotion::motores_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::lynxmotion::motores_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 q1\n\
float32 q2\n\
float32 q3\n\
float32 q4\n\
float32 q5\n\
\n\
";
  }

  static const char* value(const  ::lynxmotion::motores_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::lynxmotion::motores_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::lynxmotion::motores_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.q1);
    stream.next(m.q2);
    stream.next(m.q3);
    stream.next(m.q4);
    stream.next(m.q5);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct motores_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lynxmotion::motores_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::lynxmotion::motores_<ContainerAllocator> & v) 
  {
    s << indent << "q1: ";
    Printer<float>::stream(s, indent + "  ", v.q1);
    s << indent << "q2: ";
    Printer<float>::stream(s, indent + "  ", v.q2);
    s << indent << "q3: ";
    Printer<float>::stream(s, indent + "  ", v.q3);
    s << indent << "q4: ";
    Printer<float>::stream(s, indent + "  ", v.q4);
    s << indent << "q5: ";
    Printer<float>::stream(s, indent + "  ", v.q5);
  }
};


} // namespace message_operations
} // namespace ros

#endif // LYNXMOTION_MESSAGE_MOTORES_H

