/* Auto-generated by genmsg_cpp for file /home/gaudi/ros_workspace/lynxmotion/msg/posiciones.msg */
#ifndef LYNXMOTION_MESSAGE_POSICIONES_H
#define LYNXMOTION_MESSAGE_POSICIONES_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace lynxmotion
{
template <class ContainerAllocator>
struct posiciones_ {
  typedef posiciones_<ContainerAllocator> Type;

  posiciones_()
  : X(0.0)
  , Y(0.0)
  , Z(0.0)
  {
  }

  posiciones_(const ContainerAllocator& _alloc)
  : X(0.0)
  , Y(0.0)
  , Z(0.0)
  {
  }

  typedef float _X_type;
  float X;

  typedef float _Y_type;
  float Y;

  typedef float _Z_type;
  float Z;


private:
  static const char* __s_getDataType_() { return "lynxmotion/posiciones"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "a1dfb8f61d81d8e9fe291bc0d86a2f48"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float32 X\n\
float32 Y\n\
float32 Z\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, X);
    ros::serialization::serialize(stream, Y);
    ros::serialization::serialize(stream, Z);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, X);
    ros::serialization::deserialize(stream, Y);
    ros::serialization::deserialize(stream, Z);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(X);
    size += ros::serialization::serializationLength(Y);
    size += ros::serialization::serializationLength(Z);
    return size;
  }

  typedef boost::shared_ptr< ::lynxmotion::posiciones_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lynxmotion::posiciones_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct posiciones
typedef  ::lynxmotion::posiciones_<std::allocator<void> > posiciones;

typedef boost::shared_ptr< ::lynxmotion::posiciones> posicionesPtr;
typedef boost::shared_ptr< ::lynxmotion::posiciones const> posicionesConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::lynxmotion::posiciones_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::lynxmotion::posiciones_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace lynxmotion

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::lynxmotion::posiciones_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::lynxmotion::posiciones_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::lynxmotion::posiciones_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a1dfb8f61d81d8e9fe291bc0d86a2f48";
  }

  static const char* value(const  ::lynxmotion::posiciones_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa1dfb8f61d81d8e9ULL;
  static const uint64_t static_value2 = 0xfe291bc0d86a2f48ULL;
};

template<class ContainerAllocator>
struct DataType< ::lynxmotion::posiciones_<ContainerAllocator> > {
  static const char* value() 
  {
    return "lynxmotion/posiciones";
  }

  static const char* value(const  ::lynxmotion::posiciones_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::lynxmotion::posiciones_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 X\n\
float32 Y\n\
float32 Z\n\
\n\
\n\
";
  }

  static const char* value(const  ::lynxmotion::posiciones_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::lynxmotion::posiciones_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::lynxmotion::posiciones_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.X);
    stream.next(m.Y);
    stream.next(m.Z);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct posiciones_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lynxmotion::posiciones_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::lynxmotion::posiciones_<ContainerAllocator> & v) 
  {
    s << indent << "X: ";
    Printer<float>::stream(s, indent + "  ", v.X);
    s << indent << "Y: ";
    Printer<float>::stream(s, indent + "  ", v.Y);
    s << indent << "Z: ";
    Printer<float>::stream(s, indent + "  ", v.Z);
  }
};


} // namespace message_operations
} // namespace ros

#endif // LYNXMOTION_MESSAGE_POSICIONES_H

